Repository klaasnicolaas/python-omnikinverter, pull requests merged in 2022-02, with the labels that each got.

#95 Solis wifistick alternative approach
  omnikinverter/models.py
  omnikinverter/omnikinverter.py
  tests/fixtures/status_solis.html
  tests/test_models.py
  tests/test_omnik.py
Labels: enhancement

#128 🎆Updates maintenance/license year to 2022
  .github/release-drafter.yml
  LICENSE
  README.md
  tests/fixtures/status_solis.html
Labels: maintenance

#129 Drop Python 3.8 support
  .github/workflows/linting.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .pre-commit-config.yaml
  README.md
  pyproject.toml
Labels: breaking-change

#138 Update the models list
  .github/workflows/tests.yaml
  README.md
Labels: documentation, ci
