Repository klaasnicolaas/python-omnikinverter, pull requests merged in 2022-03, with the labels that each got.

#152 Bump flake8-bandit to v3.x
  poetry.lock
  pyproject.toml
Labels: ci

#148 Apply stricter typing to this project
  .github/workflows/typing.yaml
  omnikinverter/models.py
  omnikinverter/omnikinverter.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/test_models.py
  tests/test_omnik.py
Labels: new-feature, ci

#159 test_output: source_type is "javascript", not "js"
  test_output.py
Labels: enhancement
