Repository klaasnicolaas/python-omnikinverter, pull requests merged in 2022-05, with the labels that each got.

#186 Update lock workflow
  .github/workflows/lock.yaml
Labels: ci

#134 Add TCP source for lightweight, extended data gathering
  README.md
  examples/test_output.py
  examples/test_output_tcp.py
  omnikinverter/const.py
  omnikinverter/exceptions.py
  omnikinverter/models.py
  omnikinverter/omnikinverter.py
  omnikinverter/tcp.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/fixtures/tcp_reply.data
  tests/test_models.py
  tests/test_omnik.py
Labels: new-feature, no-stale

#198 tcp: Allow `unknown0` to be `0` in addition to `UINT16_MAX`
  omnikinverter/tcp.py
Labels: bugfix

#197 tcp: Allow serial number to mismatch in reply
  omnikinverter/tcp.py
  tests/test_models.py
Labels: bugfix
