Repository klaasnicolaas/python-omnikinverter, pull requests merged in 2023-04, with the labels that each got.

#365 Fix remainder of ruff lints
  omnikinverter/omnikinverter.py
  omnikinverter/tcp.py
  pyproject.toml
  tests/test_omnik.py
  tests/test_tcp_models.py
Labels: enhancement

#361 General refactor/restructure of the project
  .flake8
  .github/dependabot.yml
  .github/workflows/linting.yaml
  .github/workflows/lock.yaml
  .github/workflows/release.yaml
  .github/workflows/requirements.txt
  .github/workflows/stale.yaml
  .github/workflows/tests.yaml
  .github/workflows/typing.yaml
  .gitignore
  .pre-commit-config.yaml
  examples/__init__.py
  examples/ruff.toml
  examples/test_default.py
  examples/test_tcp.py
  omnikinverter/models.py
  omnikinverter/omnikinverter.py
  omnikinverter/tcp.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/ruff.toml
  tests/test_models.py
  tests/test_omnik.py
  tests/test_tcp_models.py
Labels: refactor

#369 tests: Replace deprecated `asynctest` with manual TCP `socket` in `Thread`
  omnikinverter/omnikinverter.py
  poetry.lock
  pyproject.toml
  tests/test_tcp_models.py
Labels: refactor

#375 Add python 3.11 CI check
  .github/workflows/tests.yaml
  pyproject.toml
Labels: ci
