Repository klaasnicolaas/python-omnikinverter, pull requests merged in 2023-05, with the labels that each got.

#396 Fix issue with github actions
  .github/workflows/labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/release.yaml
  .github/workflows/tweet-release.yaml
  .yamllint
Labels: ci

#376 tcp: Make firmware strings (in packet suffix) optional
  omnikinverter/models.py
  omnikinverter/tcp.py
  pyproject.toml
  tests/fixtures/tcp_reply_no_firmware.data
  tests/test_tcp_models.py
Labels: no-stale, refactor

#399 Start using PyPi trusted publishing
  .github/workflows/release.yaml
Labels: ci

#339 Wrap TCP request reading in `async_timeout.timeout()`
  omnikinverter/omnikinverter.py
  tests/test_tcp_models.py
Labels: bugfix, no-stale
